# Generated by Django 2.2.16 on 2021-08-18 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"verbose_name_plural": "Комментарии"},
        ),
        migrations.AlterModelOptions(
            name="review",
            options={"verbose_name_plural": "Отзывы"},
        ),
        migrations.AlterField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор комментария",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="review",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="reviews.Review",
                verbose_name="Отзыв",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.TextField(verbose_name="Текст комментария"),
        ),
        migrations.AlterField(
            model_name="review",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор отзыва",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="pub_date",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Дата отзыва"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="text",
            field=models.CharField(
                max_length=200, verbose_name="Текст отзыва"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="title",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews_title",
                to="reviews.Title",
                verbose_name="Произведение",
            ),
        ),
        migrations.AlterField(
            model_name="title",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="titles",
                to="reviews.Category",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="title",
            name="year",
            field=models.PositiveSmallIntegerField(
                verbose_name="Год выпуска"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.TextField(
                blank=True, null=True, verbose_name="user_bio"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=150, unique=True, verbose_name="user_email"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "user"),
                    ("moderator", "moderator"),
                    ("admin", "admin"),
                ],
                default="user",
                max_length=150,
                verbose_name="user_role",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="review",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                fields=("title", "author"),
                name="unique_togather_title_author",
            ),
        ),
    ]
