# Generated by Django 2.2.16 on 2021-08-11 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20210811_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_status',
            new_name='role',
        ),
    ]
