# Generated by Django 2.2.16 on 2021-08-18 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20210818_1222'),
        ('reviews', '0002_auto_20210818_1220'),
    ]

    operations = [
    ]
